### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SMATTHH** [RichardHooijmaijers/shinyMixR#10]
HI, While trying to install shinyMixR from Github using devtools, I am getting the following error and the installation is aborted:
Execution halted
ERROR: lazy loading failed for package 'shinyMixR'

Any idea?

**Comment by RichardHooijmaijers** [comment]
Sorry for the late reaction. Could you please provide the result from `sessionInfo()` in R? It will make it a lot easier to pinpoint the exact problem. Thanks

**Comment by RichardHooijmaijers** [comment]
It seem you do not have all required R packages installed that are necessary for shinyMixR. Could you try to install the following packages: `install.packages(c("shiny","gridExtra","collapsibleTree","shinyAce","DT","xpose","xpose.nlmixr","shinydashboard","stringi","R3port","whisker","nlme"))` and afterwards try to install shinyMixR again?

**Comment by SMATTHH** [comment]
Thanks, it looks like xpose.nlmixr is not installing, I wonder if it is
because I am installing it on R version 3.6.1

**Comment by RichardHooijmaijers** [comment]
Currently `xpose.nlmixr` is no longer available on CRAN due to a dependency issue. Could you try installing the github version instead: `devtools::install_github('nlmixrdevelopment/xpose.nlmixr')` ?

**Comment by SMATTHH** [comment]
I was trying the github version, when it did not work.

**Comment by RichardHooijmaijers** [comment]
That's strange. It could be a matter of the sequence in which you install packages. Could you try to first install xpose (from CRAN) followed by xpose.nlmixr (from github). If this does not work could you provide the exact error message that you receive?

**Comment by RichardHooijmaijers** [comment]
seems to be solved?
