### ISSUE TITLE
R CMD check fails  because of missing lines in DESCRIPTION file

### ISSUE THREAD

**Issue by bruc** [RichardHooijmaijers/shinyMixR#12]
In our R environment, we run R CMD check on every package we install, and shinyMixR fails because there is no Author: or Maintainer: entries in the DESCRIPTION file. We are running R-3.5.2. Would you please add these two entries?

Thank you.

**Comment by RichardHooijmaijers** [comment]
There was an `Authors@R` field present in the description that also holds the info for maintainer. I guess for older R versions this is not fully accepted, so I included the two separate fields also in the latest version for backwards compatibility.  Please let me know if this works for you, as I could not fully test it with this version of R on my system

**Comment by mattfidler** [comment]
I think devtools creates this when building the package.

**Comment by bruc** [comment]
@RichardHooijmaijers yes it works for us -- thanks!

We're running R-3.5.2.
