### ISSUE TITLE
Feature Request:  Support Simulations?

### ISSUE THREAD

**Issue by billdenney** [RichardHooijmaijers/shinyMixR#13]
I found myself looking to be able to support generalized simulations from an nlmixr model, and I thought that I should check here.  I don't see it in the description of what is available, so I thought I should ask:  Does this also support running simulations from the models?

What I'm hoping for may be out of scope, but perhaps it would make sense in a companion package, instead:

* Take in an nlmixr model (or perhaps an RxODE model, too)
* Automatically create a simulation interface that would allow for:
    * Dosing into any compartment (where the compartments are detected from the model) and the dosing can be on any schedule
    * Simulate either fixed effects only or with full variability
    * Visualization of either a single line for mean effects or a summary plot with intervals shaded.  You can select the compartment(s) for visualization.

I think that most of the parts of this already exist within nlmixr and RxODE, but I don't think that they have been connected to a Shiny interface.  (Or, if I'm wrong, I'd love to hear about it.)

**Comment by RichardHooijmaijers** [comment]
Currently shinyMixR does not provide such functionality, but it sound very interesting! I know some efforts have already been done but I am not fully aware of the status of this project. I guess @mattfidler knows a bit more about it. I think it would be good to see what is already available and build on that, perhaps make it into a separate package. In a last step it would be cool if this package can be linked to shinyMixR. In this case it can be used both within the interface and in a stand-alone environment

**Comment by mattfidler** [comment]
There was something, but I cannot find the code;  I'm trying to see if someone knows where it is.

There is also `rxShiny` which can be adapted.

**Comment by billdenney** [comment]
At a glance, rxShiny is something that could be adapted to my needs.  If the other code doesn't appear, then I'll probably make some suggested modifications to rxShiny as a PR.

**Comment by mattfidler** [comment]
I have requested the code from the author and the summer internship advisor;  We will see if it shows up.

**Comment by mattfidler** [comment]
The code showed up;  I will try to upload it tomorrow; With rolling blackouts, power outages etc, it may be difficult for me.  Everything should normalize by next week, though.

**Comment by mattfidler** [comment]
Uploaded here:

https://github.com/nlmixrdevelopment/shinyClinPharmNlmixr/blob/main/app2808.R

**Comment by mattfidler** [comment]
It probably needs some more work to make it generalizable.

**Comment by billdenney** [comment]
Thanks, @mattfidler.  I'll move the conversation over to a new issue in that repo since it doesn't appear to apply here.
