### ISSUE TITLE
shinyMixR failed in Win 10

### ISSUE THREAD

**Issue by mattfidler** [RichardHooijmaijers/shinyMixR#7]
https://github.com/nlmixrdevelopment/nlmixr/issues/129
When I tried to run 'run1', I got this error msg. Is there ways to fix this?

_**************C:/Users/User/Documents/shinyMixR/temp/run1.prog.txt**************_
Loading required package: nlme
Loading required package: RxODE
Error: unexpected '}' in:
" data_nlm <-
}"
Execution halted

**Comment by RichardHooijmaijers** [comment]
Is it possible to share a bit more information? I would like to know the version of R and the package versions for nlmixr/RxODE/shinyMixR. Furthermore it would help if the model and dataset can be shared. This will make it a lot easier to pinpoint the problem :)

**Comment by sliao99** [comment]
[64-bit] C:\Program Files\R\R-3.5.2'
The shinyMixR is the most recent one and the instruction dated 2018-04-06.
I tried the run1 without any changes from the package.

**Comment by sliao99** [comment]
I just tried to follow the instruction to install the package and run the example in the instruction.

**Comment by RichardHooijmaijers** [comment]
It looks like something went wrong with the installation of one of the packages. The easiest way to 
test this and to pinpoint the exact problem is to run the installation test:

[https://raw.githubusercontent.com/nlmixrdevelopment/nlmixr/master/build/test_install.R](url)

Could you run this and report back the results?

**Comment by sliao99** [comment]
[error.txt](https://github.com/RichardHooijmaijers/shinyMixR/files/2881532/error.txt)

I run the test_install.R and I got one error shown below:

Correct R version: Yes, R version 3.5.2 (2018-12-20)
RxODE installed: Yes
Python installed: Yes, Python 3.7.1
sympy installed: Yes
devtools package installed: Yes
Error : 'find_rtools' is not an exported object from 'namespace:devtools'

**Comment by RichardHooijmaijers** [comment]
It seems that you are missing Rtools wich is necessary to be able to work with nlmixr. On the github page of nlmixr there are instructions on how to install this:
[https://github.com/nlmixrdevelopment/nlmixr](url)
Perhaps it is necessary to reinstall the R packages afterwards. You can check if the installation was successful by rerunning the test_install script

**Comment by mattfidler** [comment]
@sliao99  can you try the install script again?

Devtools no longer exports `find_rtools` so I updated the install check script.
