### ISSUE TITLE
Typesetting nlmixr model equations - Feature request

### ISSUE THREAD

**Issue by mattfidler** [RichardHooijmaijers/shinyMixR#8]
HI Richard,

I wanted to let you know that nlmixr is going to be using symengine in the future (when they release it on CRAN) and drop the python dependency.

One of the things that nlmixr/RxODE does is load the models into symengine.  There is a possibility we can leverage this to add equations to the automated reporting you already have since they will be exporting this method.

Just a feature request that I think could be valuable.  I'm unsure if you are working with PharmTeX, but it could be useful there too.  The key is to use the `codegen` function. 

What do you think?

**Comment by RichardHooijmaijers** [comment]
Hi Matt,

Sorry about the late response, I kind of missed this issue.. I think it is interesting to include equations in the reporting output. Currently I am unsure how this can be done. Maybe we can discuss this issue offline?

**Comment by mattfidler** [comment]
Sure.  Some time next year?

Let me know when you are available.

**Comment by RichardHooijmaijers** [comment]
Great, will follow this up with mail!
